name: water_reminder_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  go_router: ^16.0.0
  flutter_svg: ^2.2.0
  get_it: ^8.0.3
  dio: ^5.8.0+1
  get: ^4.7.2
  equatable: ^2.0.7
  flutter_pretty_dio_logger: ^3.0.0
  connectivity_plus: ^6.1.4
  fl_chart: ^1.0.0
  hive: ^2.2.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.0
  permission_handler: ^12.0.1
  foundation: ^0.0.5
#  flutter_timezone: ^4.1.1
#  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/water.png
    - assets/images/120.png
    - assets/images/250.png
    - assets/images/500.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
